# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on  
    runs-on: [ windows-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5 
      
      - name: Restore NuGet packages
        run: nuget restore TicTocToe.sln
      
      - name: Build the Solution
        run: msbuild TicTocToe.sln /p:configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1 
        with:
          name: Repository BackUp
          path: ${{ github.workspace }}
      
      - name: collect artifacts
        run: |
          mkdir D:\a\TicTocToeCI\TicTocToeCI\Artifacts
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\Autofac.dll D:\a\TicTocToeCI\TicTocToeCI\Artifacts\Autofac.dll
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\TicTocLib.dll D:\a\TicTocToeCI\TicTocToeCI\Artifacts\TicTocLib.dll
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\TicTocToe.dll D:\a\TicTocToeCI\TicTocToeCI\Artifacts\TicTocToe.dll
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\TicTocToe.dll.config D:\a\TicTocToeCI\TicTocToeCI\Artifacts\TicTocToe.dll.config
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\TicTocToe.exe D:\a\TicTocToeCI\TicTocToeCI\Artifacts\TicTocToe.exe
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\TicTocToe.runtimeconfig.json D:\a\TicTocToeCI\TicTocToeCI\Artifacts\TicTocToe.runtimeconfig.json            
          cp D:\a\TicTocToeCI\TicTocToeCI\tutorial\Tutorial.html D:\a\TicTocToeCI\TicTocToeCI\Artifacts\Tutorial.html
            
      - name: Upload a Build Artifact 2
        uses: actions/upload-artifact@v2.2.1 
        with:
          name: Release
          path: D:\a\TicTocToeCI\TicTocToeCI\Artifacts
