# Workflow to use NUKE with GitHubActions
# credits to https://rodneylittlesii.com/posts/topic/building-github-actions-with-nuke
name: Build with NUKE

# only branch master on push and pull requests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    
    steps:
      - uses: actions/checkout@v2    
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      
      # here comes the tricky part
      - name: Build mit NUKE ausführen
        run: 
          sudo bash ${GITHUB_WORKSPACE}/build.sh --target Compile --configuration Release      
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1 
        with:
          name: Repository BackUp by NUKE
          path: ${{ github.workspace }}
      
      # this is more simple then do this by NUKE itselfs
      - name: collect artifacts
        run: |
          mkdir /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/ArtifactsNUKE
          cp /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/Autofac.dll /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/ArtifactsNUKE/Autofac.dll
          cp /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/TicTocLib.dll /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/ArtifactsNUKE/TicTocLib.dll
          cp /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/TicTocToe.dll /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/ArtifactsNUKE/TicTocToe.dll
          cp /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/TicTocToe.dll.config /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/ArtifactsNUKE/TicTocToe.dll.config
          cp /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/TicTocToe.exe /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/ArtifactsNUKE/TicTocToe.exe
          cp /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/TicTocToe.runtimeconfig.json /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/ArtifactsNUKE/TicTocToe.runtimeconfig.json            
          cp /home/runner/work/TicTocToeCI/TicTocToeCI/tutorial/Tutorial.html /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/ArtifactsNUKE/Tutorial.html
            
      - name: Upload a Build Artifact 2
        uses: actions/upload-artifact@v2.2.1 
        with:
          name: Release by NUKE
          path: /home/runner/work/TicTocToeCI/TicTocToeCI/TicTocLib/bin/Release/netcoreapp3.1/ArtifactsNUKE
