# Workflow to use NUKE with GitHubActions
# credits to https://rodneylittlesii.com/posts/topic/building-github-actions-with-nuke
name: Build with NUKE

# only branch master on push and pull requests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    
    steps:
      - uses: actions/checkout@v2    
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      
      - name: Update NET with 5.0
        run: |
          dotnet tool update -g dotnet-vs
          vs install preview -sku:enterprise --quiet +Microsoft.VisualStudio.Component.ManagedDesktop.Core +Microsoft.NetCore.Component.DevelopmentTools
          echo "##vso[task.prependpath]$(vs where preview --prop=InstallationPath)\MSBuild\Current\Bin"
      
      # here comes the tricky part
      - name: Build mit NUKE ausführen
        run: 
          sudo bash ${GITHUB_WORKSPACE}/build.sh --target Compile
