# Workflow to use NUKE with GitHubActions
# credits to https://rodneylittlesii.com/posts/topic/building-github-actions-with-nuke
name: Build with NUKE

# only branch master on push and pull requests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    
    steps:
      - uses: actions/checkout@v2    
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      
      # here comes the tricky part
      - name: Build mit NUKE ausführen
        run: 
          sudo bash ${GITHUB_WORKSPACE}/build.sh --target Compile      
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1 
        with:
          name: Repository BackUp by NUKE
          path: ${{ github.workspace }}
      
      # this is more simple then do this by NUKE itselfs
      - name: collect artifacts
        run: |
          mkdir D:\a\TicTocToeCI\TicTocToeCI\ArtifactsNUKE
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\Autofac.dll D:\a\TicTocToeCI\TicTocToeCI\ArtifactsNUKE\Autofac.dll
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\TicTocLib.dll D:\a\TicTocToeCI\TicTocToeCI\ArtifactsNUKE\TicTocLib.dll
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\TicTocToe.dll D:\a\TicTocToeCI\TicTocToeCI\ArtifactsNUKE\TicTocToe.dll
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\TicTocToe.dll.config D:\a\TicTocToeCI\TicTocToeCI\ArtifactsNUKE\TicTocToe.dll.config
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\TicTocToe.exe D:\a\TicTocToeCI\TicTocToeCI\ArtifactsNUKE\TicTocToe.exe
          cp D:\a\TicTocToeCI\TicTocToeCI\TicTocToe\bin\Release\netcoreapp3.1\TicTocToe.runtimeconfig.json D:\a\TicTocToeCI\TicTocToeCI\ArtifactsNUKE\TicTocToe.runtimeconfig.json            
          cp D:\a\TicTocToeCI\TicTocToeCI\tutorial\Tutorial.html D:\a\TicTocToeCI\TicTocToeCI\ArtifactsNUKE\Tutorial.html
            
      - name: Upload a Build Artifact 2
        uses: actions/upload-artifact@v2.2.1 
        with:
          name: Release by NUKE
          path: D:\a\TicTocToeCI\TicTocToeCI\ArtifactsNUKE
